export const CONFIGURATION = '__CONFIGURATION__'
export const ATTRIBUTES = '__ATTRIBUTES__'
export const PROCESSOR = '__PROCESSOR__'
export const PRE_PROCESSOR = '__PRE_PROCESSOR__'
export const CREATE_COMPONENT = '__CREATE__COMPONENT__'
export const GET_NAME = '__GET_NAME__'
export const CREATE_SELECTOR = '__CREATE__SELECTOR__'
